NAME = AOC12
DESCRIPTION = "Advent of Code 2024, Day 12, Part 1"
COMPRESSED = YES
ARCHIVED = YES
STACK_HIGH = D052C6

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

include $(shell cedev-config --makefile)
